name: 'Setup Javascript'
description: 'Setup a Javascript environment ready to run the Truecolors code'
inputs:
  onlyProduction:
    description: Only install production dependencies
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    # Make sure Corepack is properly enabled before any yarn commands
    - name: Enable and prepare Corepack
      shell: bash
      run: |
        corepack enable
        corepack prepare --activate
        # Force the use of corepack-managed yarn
        node --no-warnings -e "const fs=require('fs'); const path=require('path'); const yarnPath=path.join(process.env.HOME, '.corepack/yarn/current/bin/yarn'); if(!fs.existsSync(yarnPath)) { console.error('Corepack yarn installation not found.'); process.exit(1); }"
        which yarn
        yarn --version

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install all yarn packages
      shell: bash
      run: yarn install --immutable
      if: inputs.onlyProduction == 'false'

    - name: Install all production yarn packages
      shell: bash
      run: yarn workspaces focus --production
      if: inputs.onlyProduction != 'false'
