name: 'Setup Javascript'
description: 'Setup a Javascript environment ready to run the Truecolors code'
inputs:
  onlyProduction:
    description: Only install production dependencies
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    # Make sure Corepack is properly enabled before any yarn commands
    - name: Enable and prepare Corepack
      shell: bash
      run: |
        # Enable Corepack and prepare Yarn
        corepack enable
        corepack prepare --activate
        
        # Fix PATH to ensure we're using the Corepack-managed Yarn
        export PATH="$(npm config get prefix)/lib/node_modules/.bin:$PATH"
        
        # Manually create a wrapper script for Yarn if needed
        if ! which yarn | grep -q "corepack/yarn"; then
          mkdir -p ~/.local/bin
          cat > ~/.local/bin/yarn <<EOL
        #!/bin/bash
        exec "$(which node)" "$(which corepack)" yarn "\$@"
        EOL
          chmod +x ~/.local/bin/yarn
          export PATH="$HOME/.local/bin:$PATH"
        fi
        
        # Print diagnostic information
        echo "Using Yarn from: $(which yarn)"
        echo "Yarn version: $(yarn --version)"
        
        # Make PATH changes available to subsequent steps
        echo "PATH=$PATH" >> $GITHUB_ENV

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install all yarn packages
      shell: bash
      run: yarn install --immutable
      if: inputs.onlyProduction == 'false'

    - name: Install all production yarn packages
      shell: bash
      run: yarn workspaces focus --production
      if: inputs.onlyProduction != 'false'
