# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks
# NOTE: Crowdin integration has been disabled in this project. All translations are managed locally.

# YAML normalization config
---
# How to normalize keys: remove_unused, add_missing, or normalize_all (default)
normalize: normalize_all

# Paths or globs to scan for Rb files
# ruby:
#  - 'app/**/*.rb'
#  - 'lib/**/*.rb'

# Paths or globs to scan for YAML files
yaml:
  - 'config/locales/**/*.yml'

# What root keys to normalize
# Defaults to all root keys
# roots: ['en']

# Paths or globs to exclude from scanning and normalization
# This can be used to refine the above includes
# exclude:
#   - 'app/assets/javascripts/translations.js'

# Sort order
# By default, alphabetical sorting is used
sort: true

# YAML writer options
write:
  line_width: ~ # No line width limit
  format_keys: false # Do not add/remove keys, only normalize values

# Output translation data using the given representation
# Available: i18n, json, yaml, yaml_po
data_output:
  write:
    format: yaml

# Default locale
base_locale: en

# The "main" locale.
data:
  read:
    - config/locales/%{locale}.yml
    - config/locales/**/*.%{locale}.yml

  write:
    - ['{devise,simple_form,doorkeeper}.*', 'config/locales/\1.%{locale}.yml']
    - config/locales/%{locale}.yml

  yaml:
    write:
      line_width: -1

search:
  paths:
    - app/
    - config/navigation.rb

  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/views

  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos

ignore_missing:
  - 'activemodel.errors.*'
  - 'activerecord.attributes.*'
  - 'activerecord.errors.*'
  - '{pagination,doorkeeper}.*'
  - '{date,datetime,time,number}.*'
  - 'errors.messages.*'
  - 'activerecord.errors.models.doorkeeper/*'
  - 'sessions.{browsers,platforms}.*'
  - 'application_mailer.salutation'
  - 'errors.500'
  - 'auth.providers.*'

ignore_unused:
  - 'activemodel.errors.*'
  - 'activerecord.attributes.*'
  - 'activerecord.errors.*'
  - '{devise,pagination,doorkeeper}.*'
  - '{date,datetime,time,number}.*'
  - 'simple_form.{yes,no,recommended,not_recommended,overridden}'
  - 'simple_form.{placeholders,hints,labels}.*'
  - 'simple_form.{error_notification,required}.:'
  - 'errors.messages.*'
  - 'activerecord.errors.models.doorkeeper/*'
  - 'errors.429'
  - 'admin.accounts.roles.*'
  - 'admin.action_logs.actions.*'
  - 'admin.reports.summary.action_preambles.*'
  - 'admin.reports.summary.actions.*'
  - 'admin_mailer.new_appeal.actions.*'
  - 'statuses.attached.*'
  - 'move_handler.carry_{mutes,blocks}_over_text'
  - 'admin_mailer.*.subject'
  - 'user_mailer.*.subject'
  - 'notification_mailer.*'
  - 'imports.overwrite_preambles.{following,blocking,muting,domain_blocking,bookmarks,lists}_html.*'
  - 'imports.preambles.{following,blocking,muting,domain_blocking,bookmarks,lists}_html.*'
  - 'mail_subscriptions.unsubscribe.emails.*'
  - 'preferences.other' # some locales are missing other keys, therefore leading i18n-tasks to detect `preferences` as plural and not finding use
  - 'edit_profile.other' # some locales are missing other keys, therefore leading i18n-tasks to detect `preferences` as plural and not finding use

ignore_inconsistent_interpolations:
  - '*.one'
