name: Asset Precompilation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'stable-*'

jobs:
  precompile-assets:
    runs-on: ubuntu-latest
    
    env:
      RAILS_ENV: production
      NODE_ENV: production
      PRECOMPILING_ASSETS: true
      CI: true
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libidn11-dev
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          
      - name: Set up Javascript environment
        uses: ./.github/actions/setup-javascript
        with:
          onlyProduction: 'true'
          
      - name: Install dependencies
        run: |
          bundle config set --local frozen false
          bundle install --jobs 4 --retry 3
          
      - name: Precompile assets
        run: |
          echo "Setting up asset precompilation environment..."
          bundle exec rake assets:precompile
          
      - name: Check asset size
        run: |
          du -h -d 1 public/assets
          
      - name: Cache precompiled assets
        uses: actions/cache@v3
        with:
          path: public/assets
          key: ${{ runner.os }}-assets-${{ github.sha }} 