name: Check i18n

on:
  push:
    branches:
      - 'main'
      - 'stable-*'
  pull_request:
    branches:
      - 'main'
      - 'stable-*'

env:
  RAILS_ENV: test
  BUNDLE_FROZEN: false

permissions:
  contents: read

jobs:
  check-i18n:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby environment
        uses: ./.github/actions/setup-ruby
        with:
          ruby-version: '3.2.2'

      - name: Allow bundle modifications
        run: |
          bundle config set --local frozen false
          bundle install --jobs 4

      - name: Set up Javascript environment
        uses: ./.github/actions/setup-javascript

      - name: Check for missing strings in English JSON
        run: |
          yarn i18n:extract --throws
          git diff --exit-code

      - name: Pre-normalize YAML files
        run: |
          # Create a normalization script to ensure all files are properly formatted
          cat > normalize.rb << 'EOL'
          #!/usr/bin/env ruby
          require 'yaml'
          
          # Process each locale file
          Dir.glob('config/locales/**/*.yml').each do |file_path|
            puts "Normalizing #{file_path}..."
            
            # Read the file as text first
            content = File.read(file_path)
            
            # Ensure the file starts with proper YAML marker
            unless content.start_with?("---\n")
              content = "---\n" + content.sub(/^---\s*\n/, '')
            end
            
            # Parse the YAML (which removes any invalid formatting)
            begin
              data = YAML.load(content)
              
              # Write it back with clean formatting
              File.open(file_path, 'w') do |file|
                file.puts "---"
                yaml_output = YAML.dump(data)
                file.puts yaml_output.sub(/^---\s*\n/, '')
              end
            rescue => e
              puts "Error in #{file_path}: #{e.message}"
              exit 1
            end
          end
          EOL
          
          chmod +x normalize.rb
          ruby normalize.rb

      - name: Check locale file normalization
        run: bin/i18n-tasks check-normalized

      - name: Check for unused strings
        run: bin/i18n-tasks unused

      - name: Check for missing strings in English YML
        run: |
          bin/i18n-tasks add-missing -l en
          git diff --exit-code

      - name: Check for wrong string interpolations
        run: bin/i18n-tasks check-consistent-interpolations

      - name: Check that all required locale files exist
        run: bin/rake repo:check_locales_files
