name: Normalize i18n files

on:
  workflow_dispatch: # Manual trigger option
  pull_request:
    paths:
      - "config/locales/**/*.yml"

permissions:
  contents: write

jobs:
  normalize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          gem install i18n-tasks
      
      - name: Normalize i18n files
        run: |
          # Create a simpler normalization for each file
          for file in config/locales/*.yml; do
            echo "Normalizing $file..."
            # Ensure the file starts with proper YAML format marker
            if ! grep -q "^---" "$file"; then
              sed -i '1s/^/---\n/' "$file"
            fi
          done
      
      - name: Run i18n-tasks normalize
        run: |
          i18n-tasks normalize --keep-order --no-sort --line-width=999999
      
      - name: Check if there are changes
        id: git-check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes if any
        if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config/locales/
          git commit -m "Normalize i18n files [skip ci]"
          git push
          
      - name: Add changes to pull request
        if: steps.git-check.outputs.changes == 'true' && github.event_name == 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config/locales/
          git commit -m "Normalize i18n files"
          git push 