name: Normalize ALL i18n Files

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  normalize-i18n:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Normalize all locale files
        run: |
          # Create a normalization script
          cat > normalize.rb << 'EOL'
          #!/usr/bin/env ruby
          require 'yaml'
          
          # Process each locale file
          Dir.glob('config/locales/**/*.yml').each do |file_path|
            puts "Normalizing #{file_path}..."
            
            # Read the file as text first
            content = File.read(file_path)
            
            # Ensure the file starts with proper YAML marker
            unless content.start_with?("---\n")
              content = "---\n" + content.sub(/^---\s*\n/, '')
            end
            
            # Parse the YAML (which removes any invalid formatting)
            begin
              data = YAML.load(content)
              
              # Write it back with clean formatting
              File.open(file_path, 'w') do |file|
                file.puts "---"
                yaml_output = YAML.dump(data)
                file.puts yaml_output.sub(/^---\s*\n/, '')
              end
              
              puts "  ✓ #{file_path} successfully normalized"
            rescue => e
              puts "  ✗ Error in #{file_path}: #{e.message}"
              exit 1 # Fail the workflow if any file can't be normalized
            end
          end
          
          puts "All locale files normalized successfully."
          EOL
          
          # Run the normalization script
          chmod +x normalize.rb
          ruby normalize.rb

      - name: Verify normalization with i18n-tasks
        run: |
          # Install i18n-tasks gem
          gem install i18n-tasks
          
          # Run the check to ensure all files are normalized now
          i18n-tasks check-normalized

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - i18n Normalizer"
          git add config/locales/
          git commit -m "Normalize ALL i18n YAML files [skip ci]" || echo "No changes to commit"
          git push 