name: Normalize ALL i18n Files

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  normalize-i18n:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Install i18n-tasks and dependencies
        run: |
          gem install i18n-tasks
          bundle config set --local frozen false
          bundle install --jobs 4
          echo "i18n-tasks version: $(i18n-tasks --version)"

      - name: Check permissions on config/locales
        run: |
          ls -la config/
          ls -la config/locales/ || echo "Directory listing failed"
          chmod -R u+w config/locales/

      - name: Create i18n-tasks config if it doesn't exist
        run: |
          if [ ! -f config/i18n-tasks.yml ]; then
            echo "Creating default i18n-tasks.yml config file"
            i18n-tasks init
          fi

      - name: Normalize files using i18n-tasks directly
        run: |
          echo "Normalizing locale files with i18n-tasks..."
          i18n-tasks normalize
          echo "Normalization with i18n-tasks completed"

      - name: Verify normalization
        run: |
          echo "Verifying normalization..."
          i18n-tasks check-normalized || (echo "::warning::Some files could not be fully normalized, but continuing" && exit 0)

      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - i18n Normalizer"
          
          if git diff --name-only | grep -q "\.yml$"; then
            echo "Changes detected, committing..."
            git add config/locales/
            git commit -m "Normalize ALL i18n YAML files [skip ci]"
            git push || echo "::warning::Failed to push changes, but workflow will continue"
          else
            echo "No changes to commit"
          fi 