name: Test libvips

on:
  push:
    branches:
      - 'main'
      - 'stable-*'
    paths:
      - '.github/workflows/test-libvips.yml'
      - 'Gemfile*'
      - '**/*.rb'
  pull_request:
    branches:
      - 'main'
      - 'stable-*'

env:
  BUNDLE_FROZEN: false
  GITHUB_RSPEC: ${{ github.event.pull_request && 'true' }}
  MASTODON_USE_LIBVIPS: true
  # Add encryption keys
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}
  # Add other essential secrets
  SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
  OTP_SECRET: ${{ secrets.OTP_SECRET }}
  # Add fetch replies configuration with default values
  FETCH_REPLIES_ENABLED: false
  FETCH_REPLIES_COOLDOWN_MINUTES: 1
  FETCH_REPLIES_INITIAL_WAIT_MINUTES: 2
  FETCH_REPLIES_MAX_GLOBAL: 1000
  FETCH_REPLIES_MAX_SINGLE: 500
  FETCH_REPLIES_MAX_PAGES: 500

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby environment
        uses: ./.github/actions/setup-ruby
        with:
          ruby-version: '3.2.2'

      - name: Allow bundle modifications
        run: |
          bundle config set --local frozen false
          bundle install --jobs 4

      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev

      - name: Test libvips
        run: |
          bundle exec ruby -e "require 'vips'; puts Vips::LIBRARY_VERSION"
